id: 21b97211-f097-42b4-936e-a2ecf7fc27bc
<<<<<<< HEAD
full_slug: sap-ldp-logs-solution-setup
=======
full_slug: sap-logs-on-ldp-solution-setup
reference_category: hosted-private-cloud-sap-ovhcloud-observability
>>>>>>> 52a51e141e (feat: added docs for the new feature SAP logs on OVHcloud Logs Data Platform)
